import Layout from '../Layout';

export default function Catcher() {
  return (
    <Layout>
      <article className="prose prose-lg lg:prose-xl leading-relaxed indent-8 mx-auto px-4 py-12">
        <h1 className="text-5xl font-extrabold text-center text-slate-900 mb-10 leading-tight">
            False Maturity, Exploration, and Conviction in Teenage Authenticity
        </h1>
        <p>
            The novels Catcher in the Rye and Persepolis follow two young adults, Holden Caulfield and Marjane (Marji) Satrapi, as they navigate authenticity in both themselves and the world of adults around them as they approach maturity. At only 10 years old, Marji is thrust into a new, repressive environment as the Islamic Revolution is waged around her. She is forced into maturity as a result of the war, watching her family take part in activism and attempting to join them only to be met by resistance from the harsh rules that dictate the lives of women in Tehran, as well as the unyielding force of the repressive teachings of school. In contrast, Holden suffers from stereotypical teenage struggles: everything from depression and anxiety, to resentment for the world around him, all while living the privileged life of a young man in prep school, raised on 71st and Fifth. He believes he is surrounded by “phonies,” or people who fail to be genuine in how they present themselves to the world. While Holden characterizes himself to be generally apathetic, his intense focus on phoniness demonstrates the fact that he does, indeed, care about something, though he uses the so-called lack of authenticity to refuse entry into manhood. Both Marji and Holden share the experience of being thrust into the adult world by the changing environment around them and the changes in their bodies, though the worlds in which they do so differ greatly.
        </p>
        <p>
            At the close of Persepolis, Marji leaves Tehran in an act which launches her search for an authentic life. After spending four years railing against the false teachings of her school, Marji and her family decide she would be better off living in the freedom of Europe. As her parents send her off, her father tearfully states “don’t forget who you are and where you come from,” setting the stage for her journey in Persepolis 2, in which she struggles to find balance between her new life and remembering her roots (152, Persepolis). Marji’s journey is displayed through her sexual exploration and the concurrent changes her body undergoes, as it is the greatest contrast from her limited life in Iran and represents taking actions she believes to be “adult.” While moving from place to place, as Marji continues to struggle with obeying authorities as she did as a child, Marji soon ends up living with the very western Julie. At the end of a party Julie throws one night, not only is Marji stoned, but witnessed Julie sleep with her nineteenth guy, and Marji says “that night, I really understood the meaning of ‘the sexual revolution.’ It was my first big step toward assimilating into western culture,” (34). A physical transformation joins the mental one, and soon she begins wearing makeup, dressing to the more revealing fashion of where she lives, and overall maturing into a Westerner during these formative years. Marji enjoys her social liberties, smoking to a point of coughing up blood from bronchitis, where she originally had blown out smoke and rubbed her eyes red to fake being stoned to ‘fit in.’ She undergoes a stint as a drug dealer, dates a few men–one of whom turns out to be gay, lives on the streets for a while, and calls her mother to pray for her whenever she needs to pass an exam, almost commercialising the relationship with god she, too, used to hold close. However, in the end, Marji says, “I had known a revolution…I had survived a war…and it’s a banal story of love that almost carried me away,” (87). She may be referring to being cheated on, but as a whole, the “story of love” represents how Marji forces her transformation into being a Westerner, to a point where loses herself and finally, realizes that she had spent four years ‘achieving’ authenticity, only to stray father away from that goal than she was before.
        </p>
        <p>
            After living on the streets and her bronchitis hospitalization, Marji returns to Iran, donning her veil once again and, in the end, has to decide between her family and her Western identity to discover which truly is authentic to who she is. Upon arriving at Mehrabad Airport, Marji “immediately [feels] the repressive air of [her] country,” and though she’s happy for the familiarity of it all, she soon feels “as though [she] were walking through a cemetery,” as her former home was now the remnants of a war zone (92, 97). She struggles in the post-war environment, and reconnecting with her family and friends is difficult, as what was once forbidden to all of them–everything from drugs to fashion magazines–is now something Marji has experienced herself, and no longer carries the disproportionate importance that it still does to them. Her environment and past weigh down on her and she spirals into depression, coming to the conclusion that she “was a Westerner in Iran, an Iranian in the West. [She] had no identity,” (118). Marji had explored so many facets of life at this point, yet ends up more firmly stuck between the two identities she had grappled with. After another physical transformation to ‘fit into’ her surroundings again, Marji explores her adult life in Tehran, which only serves to exemplify the contrasts between her and her loved ones. The cyclicality of returning home to undergo the same exploration of life’s offerings as she went through in Europe returns the same results; everyone else is content and adjusted to the life they live, yet Marji’s superego causes her to feel lost while indulging in the West, and repressed while abiding by the rules at home. Marji’s grandmother is the one to break her out of this rut when discussing Marji’s marriage, saying “take your time, think about it, and the day you don’t want it anymore, you leave him!” (179). Here, her husband symbolizes the West and Tehran, as Marji may have seen all both had to offer, yet never took the time to truly consider which environment she felt was more true to her. In the film, the speed with which she moves through life in both places is exhibited through constantly moving, fluid imagery, that seamlessly transitions into the next image without the rest that Marji needed to determine her preference. Taking her grandmother’s advice, Marji slows down and simply enjoys life, exploring the beauty of her country, and eventually leaves to Europe again, but with conviction in the finality of her decision.
        </p>
        <p>
            Marji’s journey for authenticity may span multiple countries and numerous years while Holden’s takes place in the small island of Manhattan, over the span of two days, yet the cores of their development are mirrors. Holden pushes back against things he believes to be shallow, inauthentic, or fake in the adult world he is entering, using it as an excuse to remain childlike in both mentality and action. He uses the term phony to represent how he cares about whether the people around him are genuine or not, yet fails to realize his own phoniness, in the form of lying and misrepresenting himself. Though Marji fights against being childlike, her impulsive actions enforce her status as such, and both characters spend their quests for authenticity exploring their inner and outer worlds. Where Marji’s outer world is Europe, Holden’s is New York, and they use the outer world as an escape from their inner worlds of home and their family. In Catcher in the Rye, Holden spends his two days living as an adult would, yet all the while ridiculing the adult world and failing to achieve satisfaction. However, seeing himself in all his immaturity and impulsivity reflected in his younger sister Phoebe is what finally causes his return home. Marji’s journey closes with leaving home, contrasting to that of Holden, but what both do in the end is realize what all young adults on the precipice of maturity eventually understand: they don’t need to abandon and forget their families for freedom, for the greatest freedom is becoming an adult while carrying their past and cherished memories with them, wherever they end up. For Holden, that meant returning home to undertake the journey of enjoying life and the beauty of his childhood, just as Marji did after taking her grandmother’s advice. As Marji already took the time to move on, she was able to leave home as a matured adult. Holden and Marji are in different stages of life, time periods, and environments, yet both undergo a search for authenticity in their inner and outer worlds that marks the transition from child to adult, exhibiting how this journey is shared by all young adults, no matter where or when they were born.
        </p>
        <hr className="my-12 border-t border-slate-300" />

        <section className="text-sm italic text-slate-700 space-y-2">
            <h2 className="font-semibold not-italic text-slate-800 pl-6 -indent-6">Works Cited</h2>
            <p className="pl-6 -indent-6">Satrapi, Marjane. <em>"Persepolis"</em></p>
            <p className="pl-6 -indent-6">Salinger, J.D. <em>"Catcher in the Rye"</em></p>
        </section>
        </article>
    </Layout>
  );
}