import Layout from '../Layout';

export default function Chinatown() {
  return (
    <Layout>
      <article className="prose prose-lg lg:prose-xl leading-relaxed indent-8 mx-auto px-4 py-12">
        <h1 className="text-5xl font-extrabold text-center text-slate-900 mb-10 leading-tight">
            The Disquieting Reality of Chinatown, One Comparable to Our Own
        </h1>
        <p>
            Roman Polanski’s Chinatown is a film noir that has gone down in history for its Oscar-winning screenplay, starring Jack Nicholson (Jack Gittes), Faye Dunaway (Evelyn Mulwray) and John Huston (Noah Cross). Gittes is a private detective, and before the main plotline even starts, the film opens to Gittes showing pictures of a woman and a man having intimate relations to his client, the distraught husband of the woman in the pictures. Investigating the infidelity of spouses does fall into the job description of a PI, but the opening is more significant for how Gittes deals with the client, Curly. Rather than taking on the brusque, offhand manner of other portrayals of detectives in old Hollywood, Gittes lands firmly in the morally and emotionally gray. He’s tortured by his past and wears a mask to project strength, yet when that inner turmoil escapes, it manifests in Gittes having a strange sort of kindness. Herein lies the relevance of the opening scene.
        </p>
        <p>
            In his dealing with the devastated Curly, Gittes seems reluctant to console the man, pouring Curly a shot with a frown, a quip, and a cigarette in mouth. However, despite Gittes’ obvious distaste for Curly’s lack of composure, only consoling words greet Curly. He goes as far as to say “I don’t want your last dime, what kind of a guy do you think I am?” (3:37) which directly opposes his assumed objective as a member of capitalist society: to always be chasing money. This scene sets the precedent not just for Gittes’ character, who we find to spend the rest of the film with the same unspoken war between his pain and his mask, but the inescapable societal injustice of his Los Angeles society. The physicalization of his mask comes when Polanski’s character, a thug, slashes Gittes’ nose, leaving Gittes with a bandage obscuring part of his face for most of the rest of the film. Such an injury creates the appearance of Gittes being a tough guy, hardened by his job, yet it contrasts with his gentler comportment. Gittes is the epitome of a man who has given up on doing the right thing, the cause of his inconsistent characterization.
        </p>
        <p>
            The next time we see Curly is near the end of the film, sitting down for supper with his family. Here we see his wife as she opens the door for Gittes. In one shaky, extended shot that follows Gittes through the door and past the wife, who freezes in recognition of him, the obscene shiner that swallows up her right eye is the star. In that moment, we recognize that Curly stayed with the cheating wife he presumably was devoted to, this assumption derived from his anguish upon finding out about her adultery. In the next moment, we notice her giant black eye and the realization hits concerning Curly’s twisted justice and Gittes’ lack of reaction to her injury or presence in the household. The one shot is impactful enough to impress upon the viewer a sense of unnerving normalcy; wives will cheat, husbands will beat them into submission, and the rest will ignore such actions. All of this plays a part in the corruption of society, which Polanski masterfully exposes.
        </p>
        <p>
            The main representation of the corruption in politics, families, and businesses is Noah Cross, the most powerful, wealthy man in Los Angeles. Gittes spent the entire film uncovering Cross’ plot to amass more money by dumping water to exacerbate the drought so that he has a monopoly on irrigation. When asked what he could possibly need more money for, Cross responds by saying “The future, Mr. Gittes! The future,” (2:02). Even though he’s on top of his community, Cross has an unquenchable greed that doesn’t care about who or what it hurts to gain more. That greed is echoed throughout society, which deepens the unusual nature of Gittes in his aforementioned anti-capitalist statement to Curly. Cross’ greatest atrocity, however, is unrelated to his immoral business tactics. We discover he raped his daughter, Mulwray, who then ran away to raise their child of incest in secret. Cross searches for her over the course of the film, and at the climax, Mulwray almost escapes from him with their daughter before she’s shot through the eye by the police.
        </p>
        <p>
            In the final, disturbing scene, Cross pulls the screaming, teenage daughter who just witnessed her mother’s gruesome death, from the car, and though a force of those meant to upkeep the law are present, not one blinks an eye. Cross, of course, owns the police, but more than that, each knows that despite the terrible fate the young girl would be sentenced to in the hands of Cross, they wouldn’t be able to fight such a powerful man. As such, they do nothing, and most likely don’t care enough anyways. Gittes is an example of one who tried, and failed. Gittes, seeing the mutilated body of a woman he cared for and the daughter she tried so hard to keep from the man taking her away, watches in dissociation and regret as he says “as little as possible,” (2:07). The line references how he previously said that when working as a police officer in Chinatown, he tried to do as little as possible because Gittes couldn’t tell if he was protecting people or hurting them when trying to do any good. In this case, his actions led to the death of Mulwray and the capture of her daughter. While this ending may have held up if he hadn’t interfered, it ended up unfolding as it did with his attempts to help them. Gittes didn’t stick to his own advice, and it came back to bite him in the end. 
        </p>
        <p>
            Chinatown displays the untouchable nature one achieves with wealth and power, in a society where wealth is power. Men trample over others in order to fulfill their greed, an act that can never be realized due to the unending nature of greed, and take what they want while others can only watch as corruption fuels their lives. Gittes’ experience in the film may have uncovered a dark truth, yet his discovery did nothing to change the course of the corruption, and the horrific final scene is not eerie due to the death or gore, but the disquieting reality of how nothing was, or could be achieved. Perhaps the most unsettling irony of all is that Polanski himself has been accused of multiple accounts of sexual assault, including rape. As part of Polanski’s prosecution, he spent his house arrest in his ski chalet in Gstaad, a luxurious place in contrast to the prison cells most others in the world would be sentenced to. While the corruption in Chinatown may seem dramatized for the big screen, the real world is rife with it as well. As Gittes said, in a line that never made it out of the original screenplay, “You gotta be rich to kill somebody, anybody, and get away with it.”
        </p>
        <hr className="my-12 border-t border-slate-300" />

        <section className="text-sm italic text-slate-700 space-y-2">
            <h2 className="font-semibold not-italic text-slate-800 pl-6 -indent-6">Works Cited</h2>
            <p className="pl-6 -indent-6">Polanski, Roman. <em>"Chinatown"</em></p>
        </section>
        </article>
    </Layout>
  );
}