import Layout from '../Layout';

export default function Leviathan() {
  return (
    <Layout>
      <article className="prose prose-lg lg:prose-xl leading-relaxed indent-8 mx-auto px-4 py-12">
        <h1 className="text-5xl font-extrabold text-center text-slate-900 mb-10 leading-tight">
            The Soul of the Commonwealth: Hobbesian Sovereignty as Reason and Nurture
        </h1>
        <p>
            In Leviathan, Thomas Hobbes defines sovereignty as the “soul of the Commonwealth,” yet through his exploration of the relationship between governance and the nature of man, he demonstrates how sovereignty is a necessary precondition to all social life and self-rule (3). The former relates to his cynical perception of man in the state of nature, which “render[s] men apt to invade and destroy one another,” and is centered around man’s fear of death and sense of self-preservation (76-77). The latter stems from his ‘liberal’ ideologies, in which sovereign power is grounded in the consent of the governed through the covenant, which demonstrates his respect for particularistic privilege (81). Both are crucial to understanding the world exhibited in Leviathan, as, upon examination the two concepts demonstrate the alignment between the needs of man and the ends of sovereignty, tied together by Hobbes’ core belief of the potential for reason in man, all of which exposes his optimistically pessimistic vision of civil society. 
        </p>
        <p>
            Hobbes’ theory of the chaos of mankind when there’s a lack of common power may be rooted in his negative view of humanity, yet allows for insight into the motivations behind why man would lay down their rights and natural liberty in order to enter into society (79). In Leviathan, all human beings are equal while not bound by the laws of civil society, in that they are all susceptible to violent death, as well as in possession of an unrestrained freedom concerning their capacity for self-defense. Morality and Justice are nonexistent, and thus man appears to be no better than beast (89). However, if humans are indistinguishable from other animals in the state of nature, why is the complex social structure of society limited to mankind? Such a difference lies in man’s potential for reason, which Hobbes positions in the world of Leviathan by stating “reason is the pace; increase of science, the way,” (26). He sees reason to be created by man in lieu of an innate skill, the ends of which lie in proceeding from one consequence to another (26). Furthermore, by his definition, science is the cumulative result of the application of reasoning over time, and thus is the knowledge of consequences (25). As such, man is capable of conjecture, a skill which enables them to weigh the benefits of joining society against the loss of freedom.
        </p>
        <p>
            Thus far, the motivation for man to enter the commonwealth may seem evident–for the sake of self preservation–yet the introduction of science reveals the nuance in such rationale. Man is not such a monotone creature as to only perceive the world from a logical viewpoint, centered around preservation; man also experiences emotion, with desire being the most relevant in this context (77). The state of nature is equivalent to a time of war for Hobbes, and thus men do not simply seek preservation upon entrance into society, but peace and the accompanying benefits of social life; during war there is no industry, ease, or sensual delight–all of which constitute passions of men, and so they are consequently inclined to lay down their rights in order to secure their desires (76, 78). Here lies the importance of science; man is capable of wielding reason in order to conclude that additional benefits reside in society beyond base preservation, and can also foresee the longevity of such advantages under sovereignty, which is in direct contrast to the constant uncertainty within a state of war. As such, the part of man’s nature which relates to the necessity of sovereignty is his potential for reason, which allows him to draw conclusions concerning the long-term security of his preservation and passions.
        </p>
        <p>
            Hobbes defines sovereignty as the “soul of the Commonwealth,” a statement which can be understood through the examination of the law and the intentions and purposes behind it (3). Upon its primary introduction, governance appears to restrict and bind the unrestrained liberty of man in the state of nature through the word of law and presence of punishments, yet Hobbes continues beyond that base explanation to reveal how “the use of laws (which are but rules authorized) is not to bind the people from all voluntary actions, but to direct and keep them in such a motion as not to hurt themselves by their own impetuous desires, rashness, or indiscretion,” (79, 229). Such an addition to the depiction of the use of laws in the world of Leviathan is crucial in softening the image of sovereign power, and exhibits respect for individuals and their rights in society. Hobbes illustrates the mandates of law as a guiding hand for all the citizens in the commonwealth through his word choices; the phrases ‘direct’ and ‘not to hurt themselves’ distinguish law from a cold, unyielding rule, and rather, imbue sovereignty with an almost maternal quality. Furthermore, he portrays the people in a manner alike to that which one may describe children, as they must be overseen in order to prevent their own injury, the implication of which is that they don’t know any better. To delineate the role of a mother, Hobbes expresses how she holds the life of her infant in her hands, as she has the options to either nourish or abandon the defenseless baby (129). Hence, when sovereignty is referred to as the ‘soul’ of the commonwealth, “giving life and motion to the whole body,” its maternal characteristic is reinforced, where the body is composed of the people in the society (3). As such, the relationship detailed between a mother and infant is equivalent to that between the soul and body, or, the sovereign and people of a commonwealth; the former has dominion over the latter through the act of nurture. Moreover, raising or ‘nourishing’ a child demands far more maternal responsibility than simply protection, and so–through the unveiled parallels–the same may be theorized of sovereignty (129). Hobbes later confirms the theory when stating the responsibilities of the sovereign to include “all other contentments of life, which every man by lawful industry, without danger or hurt to the commonwealth, shall acquire to himself,” (219). Furthermore, the expansion of the sovereign’s role encompasses the passions and needs of men, displaying the mutual alignment between them. Thus, through the exposition of the similarities between maternal and sovereign roles, the designation of the ‘soul’ can be understood and consequently wielded to reveal the ends of sovereignty. 
        </p>
        <p>
            Hobbes employs the concepts of reason, preservation, passion, and maternity, as well as the roles they play in the commonwealth and state of nature, to evidence his vision for society in Leviathan. Though he views humans as fundamentally self-serving and prone to violence–a harsh perspective on the nature of man–his explanation of sovereignty reveals a cautious optimism, hidden within the concept of man’s potential for reason and their consequent capacity for peace. 
        </p>
        <hr className="my-12 border-t border-slate-300" />

        <section className="text-sm italic text-slate-700 space-y-2">
            <h2 className="font-semibold not-italic text-slate-800 pl-6 -indent-6">Works Cited</h2>
            <p className="pl-6 -indent-6">Hobbes, Thomas. <em>"Leviathan"</em></p>
        </section>
        </article>
    </Layout>
  );
}