import Layout from '../Layout';

export default function Rousseau() {
  return (
    <Layout>
      <article className="prose prose-lg lg:prose-xl leading-relaxed indent-8 mx-auto px-4 py-12">
        <h1 className="text-5xl font-extrabold text-center text-slate-900 mb-10 leading-tight">
            From Savage Liberty to Civic Unity
        </h1>
        <p>
            The general will in The Major Political Writings of Jean-Jacques Rousseau reflects his core beliefs concerning what constructs society by tackling the underlying dialectic between freedom and a lack thereof. He begins by portraying man in the state of nature in such a manner that one can perceive the true liberty of men not bound by society, yet also understand how men could leave such a state. Man is explained to possess the quality Rousseau refers to as perfectibility, which is what differentiates man from beast, but does not make him better than those limited to their primitive state; man in nature has the “capacity as a free agent” and “it is above all in the consciousness of this freedom that the spirituality of his soul is shown” (72). The state of man when it was most alike to beast differs due to the presence of this will, and though man has yet to operate with the power of reason, thoughts, and ideas, man has a sense of his capability to transform his crude mindset and evolve. Therein lies the difference between man and beast; one can leave the form they take in the state of nature–relying solely on one’s instinct and operating based off of the fear of pain and hunger–while the other is incapable of doing so (73). However, under such circumstances man had a certain freedom as he was in complete control of himself and actions–with no subsidiaries–and most importantly had an empty brain besides the presence of fear and hunger. Living such a primal life may seem unimaginable in modern society, yet the true freedom of man in nature may in fact lie in their unburdened minds; as such, their freedom is derived from both their lack of social bindings as well as those of the mind. As such, according to Rousseau’s theorizing, man has the potential for improvement upon leaving the state of nature and the accompanying  natural freedom, though the first true step out of the primitive form man takes in the state of nature is the establishment of private property.   
        </p>
        <p>
            Though once man began interacting with other humans–going through the motions of what may be perceived to be those of a member of society–the introduction of the division of land and the resultant emergence of polity are what begin to capture Rousseau’s ideas concerning freedom and its loss. Clear inequalities between men emerged once they began mingling, and so when those possessing greater wisdom came to realize their superiority, they took advantage of those less powerful and cunning (102). Rousseau expresses how stronger men propositioned weaker men with the concept of unity for the purpose of protection and security, and thus latter group “ran towards their chains…for while they had enough reason to sense the advantages of a political establishment, they did not have enough experience to foresee its dangers,” (103). Thus, political society emerged with the power imbalances and inequalities that define any society; the rich and wise men stepped on the backs of others to augment their own personal powers, and the weaker men were crushed to the bottom ranks of society as a result. However, despite the negative aspects of entering into society, there were still clear enough ‘advantages’ for even the less wise men were to be capable of recognizing. The power gained from having numbers when out in the wild worked towards the interests of every man, and as Rousseau states, “the social order is a sacred right that serves as the basis for all others,” (164). The sanctity is derived from the method by which society is created–not nature itself–that being convention, or, the social contract between those who create or join society. 
        </p>
        <p>
            Man may be limited by the structures and laws of a government, yet through the social compact they become part of the general will and thus are capable of being one with the whole and free in a different manner. Rousseau makes the claim that “since each gives himself to all, he gives himself to no one,” defining the role of man in society to be part of a united force (173). The ‘all’ is the public, and as such, refers to the universal commitment of all citizens to the entity of the commonwealth, and thus implies how each individual is not giving up their own freedoms, but rather, becoming part of a larger body in which they retain their liberty. Since the general will is the common interest of the people, differing from the particular interests of each person, by submitting to that will, citizens paradoxically retain autonomy (182). Political society for Rousseau is beyond an absolute ruler and their subjects, but rather–due to the general will–a community in which each individual has the same power as every other citizen. Though man was free in the state of nature, they remain so in a different manner upon entering society, which is a necessary condition for their evolution and due to their perfectibility.
        </p>
        <hr className="my-12 border-t border-slate-300" />

        <section className="text-sm italic text-slate-700 space-y-2">
            <h2 className="font-semibold not-italic text-slate-800 pl-6 -indent-6">Works Cited</h2>
            <p className="pl-6 -indent-6">Rousseau, Jean Jacques. <em>"The Major Political Writings of Jean-Jacques Rousseau"</em></p>
        </section>
        </article>
    </Layout>
  );
}