import Layout from '../Layout';

export default function Trutescu() {
  return (
    <Layout>
      <article className="prose prose-lg lg:prose-xl leading-relaxed indent-8 mx-auto px-4 py-12">
        <h1 className="text-5xl font-extrabold text-center text-slate-900 mb-10 leading-tight">
            Christina Trutescu Will Never Give Up
        </h1>

        <p>
            In the heart of a labyrinthine apartment complex in Edgewater, New Jersey lives my aunt, Physician’s Assistant Christina Trutescu, with her husband and two sons. Walking through their apartment means carefully avoiding stray pieces of squashed kumatos, a pile of building blocks, and clean laundry strewn across the furniture, all while Cocomelon blares in the background. After mornings that start at the crack of dawn with the cries of Adam, still under a year old, Trutescu leaves for work in the seafoam green scrubs specific to the trauma surgery unit. Her alternative for the lightweight scrubs is a nondescript uniform of the same caliber, consisting of a colorless tee and sweats, mirrored by the rest of her family as they indulge in overstimulation. “Just make yourself happy,” she recommends. However, the controlled chaos that overwhelms this household is comforting in how it so heartily declares ‘a family lives here!’
        </p>
        <p>
            The half-finished cups of coffee that litter the staffroom of the ER are but a minor part of the vitality that characterizes the bustling hubbub of patients, staff, and loved ones in the most dynamic part of the hospital. The precision of the on-call surgeon’s hand must be flawless under the unfathomable pressure of time, a precious commodity that marks the difference between life or death. If the physician’s assistant who persistently remains at the side of the surgeon fails to anticipate each request, the perfect tandem with which they work will be broken, and could conclude the game of survival they oversee. It is here that Trutescu thrives. Her perpetual energy sustains her through the long, arduous hours in which she is employed, more than any espresso. Trutescu is fundamentally unbreakable with the support of the decade she spent familiarizing herself with the human body, as a med student, but first, as a gymnast.
        </p>
        <p>
            Born in 1990, Trutescu was raised in a tranquil house in Long Island with her older sister, Patricia, and her parents, two Romanian immigrants. Even today, their accents hold strong and at times even Trutescu slips into a certain melodic tone when in a parental position, though she was born American. From the driveway of the house you can see the climbing wisteria that allows the house to express itself brightly even when drowning under a foot of snow. The building contains a kaleidoscope of memories, from school photos to the trophies from Trutescu’s gymnastics days, standing proudly on the chipped white dresser in her childhood bedroom. Examine the boxes stuffed in the back of her closet and you would find tapes of her competitions harking back to her early days of being a gymnast.
        </p>
        <p>
            By the time she hit the age of nine, Trutescu was akin to a bee buzzing around in a still-life painting. Her favorite pastime was flipping her body through the air with only the glistening green carpet of the lawn to catch her. Trutescu’s vitality caused her mother to worry that the nine year-old would break her neck, so she swapped the unyielding ground with a foam pit, taking Trutescu to a gymnastics gym and enrolling her in classes as an outlet for her energy and all the “daredevilishness” inside of her. What Trutescu didn’t expect was to be enraptured by setting her muscles alight with the dynamic movements and economical use of strength that were required of gymnastics. Even though Trutescu started late, as the recommended age to begin training in this discipline is as young as one years old, she quickly excelled. Within a year she was already in tune with her body as she stretched it past the normal breaking point and advanced into joining a private club at ten.
        </p>
        <p>
            “We have a legacy of producing good gymnasts,” Trutescu said, about her Romanian identity. Romanian olympian Nadia Comaneci was the first gymnast to be awarded a perfect ten for an event, and Trutescu recalls “when my parents thought to enroll me, they were pretty excited.” Carrying the weight of her nation’s history on her back only fueled her unwavering drive, though she did admit, “I felt a bit more pressure because I knew where I came from and most people who were well-versed in the sport would bring it up when they met me, they’d be like oh you’re Romanian, like, no wonder you’re a gymnast, and it was kind of like oh, I hope I’m good.” Trutescu punctuates each statement with a mellow laugh, emanating the same warmth as a smoldering hearth, which has defined her throughout the decade that I’ve known her. It was inviting enough to convince my timid six year old self to step onto Wollman Rink with her, and now epitomizes her role as a mother.
        </p>
        <p>
            Trutescu’s mother was the greatest influence on and supporter of her passion, driving her to every practice and picking her up, which was no small feat considering the sheer number of practices Trutescu underwent. As she started honing her craft and winning competitions, Trutescu planned with her coach and mother to begin training with more professional teams. Her training sessions averaged a lengthy three hours a night for five days a week, and for each of those fifteen hours her mother was seated in the bleachers, cheerfully uttering encouragements. Trutescu’s competitions were mainly a family affair, but even when her father and sister were otherwise occupied, her mother always attended. “I always had a big support system, and my mom and my dad always said that however far I want to go with that they would be supporting me all the way,” Trutescu recalls. And they did, even when she reached training level nine and entered a never ending cycle of injury and rehabilitation.
        </p>
        <p>
            In total, there are ten levels of gymnastics. After completing the ten levels of training, gymnasts are considered ‘elite,’ which is when they can start competing in global competitions such as world championships and qualify for the Olympics. By the ninth level, Trutescu had solidified her desire to be a professional gymnast and was doggedly pursuing her goal. She was training 20 hours a week, a level of commitment that slashed her school day to end at 1:45PM, and continuously suffered broken ankles, sprained ankles, and ruptured achilles tendons. “I think I sprained my ankle 7 times,” Trutescu said. Such a cycle of injury is not uncommon for gymnasts, and in a 2015 study in the Orthopedic Journal of Sports Medicine, Dr. Paul Saluan determined that for every 1000 hours of training, gymnasts suffer two injuries. Accordingly, every time Trutescu was set on the path of improving her skills and rising up in her rank as a gymnast, she would suffer an injury and have to lay off of her intensive training for a few weeks. However, to keep in shape she would still undergo strength training and conditioning during those few weeks. So, she’d return to her full-time practice without proper rest and facing set backs in terms of her skills, ultimately resulting in another injury and enduring another round of the cycle. The unsustainable repetition of pushing herself past her limits not only stymied her growth as an athlete, but also chipped away at her rock-hard determination.
        </p>
        <p>
            “It was almost like I was just stuck in the same place for almost a whole year, and at that point being injured so many times made me miserable, feeling like I was never going to progress beyond the point that I was at made me miserable, so I said instead of being miserable, maybe I should just quit.” Trutescu did just that at 17 years old, and immediately faced a sense of loss unlike anything she’d experienced before. The shock of never doing that type of training again, and the loss of her purpose only traded her physical wounds for emotional ones. However, as her despair dissipated, she found light in her newfound normalcy. It was an exceptionally strange experience, but now that her training couldn’t devour all of her free time and social life anymore, she was able to enjoy her senior year of highschool.
        </p>
        <p>
            What Trutescu hadn’t realized for all those years of gymnastics was what she was missing, especially when it came to friendship. The noose of her training schedule had warded off friends and so with its release, she was able to cultivate more friendships and be a part of a bigger friend group at school, a core part of the highschool experience which had been absent from her life. Reflecting back on this time she said, “it was all very exciting after the initial shock of being taken out of something that I had done for so many years.” The simplicity of a free period is often overlooked by the majority who have them in abundance, but for Trutescu, the idea of wasting time in such a fashion was inconceivable. Not that she had much time to waste, as this was during the height of the college process, and at this point in life she was making decisions that would help shape her future.
        </p>
        <p>
            Trutescu began her college career at Stony Brook University as an economics major. However, she first toyed with the idea of entering the field of medicine due to her background in gymnastics. All the while she had been getting injured, she would research treatments for said injuries and go as far as to read books on the topic. It was there, in a budding excitement for anatomy and physiology, that her first interest in a career in healthcare began. As such, it was unfortunate that her father pushed her into a field that would mimic what he had done with business, economics, and engineering for over 20 years. Trutescu said, “I chose economics mostly because I really wanted to please my family, and especially my dad, and after choosing it I realized I wasn’t happy and so I decided to go into medicine because of that.” She may have started gymnastics because of her ceaseless energy, but the greater focus on her body and health ended up guiding her towards the career path she eventually chose and loved. Even today Trutescu is connected to her roots in the sport, often recommending aerobic exercise to patients in order to raise their heart rate for the maintenance of their health; “I realize that that probably comes from the fact that I worked out so much as a gymnast,” she said.
        </p>
        <p>
            Entering the world of healthcare is no small feat, and Trutescu wanted to be an MD or DO upon graduation, the two degrees that can make a physician. Her initial plan was to go into medicine, and she believed that this could only be possible by becoming a doctor. Accordingly, she took a post-baccalaureate program at Columbia University and completed all necessary prerequisites for med school: research, volunteering, overall gearing her resume in favor of her application. After such painstaking work, it was with great frustration that she was rejected in the first round of applications. However, Trutescu was persistent and, after deciding her application was lacking in experience, she went on to become an emergency department medical scribe at Huntingdon Hospital, where she shadowed doctors and chronicled the medical records of patients. Thinking back on this experience she said, “I was starting to feel a little bit burnt out from everything. It was 2 years at Columbia, then volunteering and applying another year, then scribing another year, and I was just trying to get my foot into the medical field, and it’s taking so long just to get into a school!” Scribing did have its benefits, though, as from her position of silent observation she was able to discover the existence of the Physician’s Assistant.
        </p>
        <p>
            In Trutescu’s first shift scribing in the emergency room there was a code blue, the dreaded time when a patient goes into cardiac arrest. Her position as scribe required her to be present in the ER for this event, and when the doctor rushed over it was as if all the knowledge in the world shrank into that one person. Striding over with a swirling sense of omniscience, the doctor seized command of the entire room, began delegating responsibility among others in the room, and ended up taking over the care of the patient. Trutescu said, “I was really in awe of that person and then I realized that that wasn’t actually a physician, and it was a physician’s assistant,” going on to wonder, “Who is this guy? Wow, I hope I’m that kind of a doctor.” After her initial interest was sparked, she began researching the profession and soon realized that there were numerous PA’s in the hospital, all of whom told her they loved their careers and highly recommended the profession to her.
        </p>
        <p>
            In the following round of med school applications, Trutescu also applied to PA school. Brimming with excitement, she swiftly completed the separate prerequisites for PA school, which included courses from psychology to microbiology at Columbia University. With her increased experience working in the field along with her extraordinary drive, she got accepted into Seton Hall University for PA school and immediately withdrew from her med school applications. The work didn’t end there, and Trutescu toiled for three years in the rigorous program, “I would wake up around 2AM, go into anatomy lab at 3AM, work on the cadaver until about 5 or 6, then study until about seven or eight when classes started, be in class until four, come back, study or another one or two hours, go to bed and then do it all over again.” Her rigorous gymnastics background had prepared her well for this grueling schedule, which ended nine months ago when she graduated and received her PA license.
        </p>
        <p>
            Amongst the five surgeons she works with at Jersey City Medical Center, Trutescu has a supervising position, though they are all supervised by the Chief Trauma Surgery PA, the unit in which they all don the aforementioned seafoam green scrubs. The Chief PA has 15-20 years of experience at the Medical Center under her belt, and as such, has guided Trutescu into the profession. “As a new graduate coming out of school, you don’t always have the confidence that you need, and so she definitely helps me and has helped me gain more confidence, and she’s helped me be more assertive,” Trutescu said. Her mentor throws her into situations she “needs to be thrown into,” as Trutescu otherwise would hesitate in the face of exiting her comfort zone to take on more responsibility. She has recounted the act of having to delegate in emergency situations as “adrenaline-pumping,” but worth it.
        </p>
        <p>
            When asked if there were moments in which she felt powerful as a PA, Trutescu responded, “Yeah actually, it’s a little scary,” the heady balance between control and chaos that defines the ER as well as her home. Trutescu has finally reached the culmination of her years laboring first as a gymnast and then in her medical pursuits, and now goes by the motto “Fortune favors the brave.” A quite apt description of her perseverance through various interests, Trutescu’s motto reflects her hardworking identity in both work and outside, as she is a PA and a mother of two. Raising children while enduring the immense stress of her job is more than an impressive feat, and Trutescu’s advice on the topic is, “if you really want to do something, and you want to do it badly enough, do it no matter what anybody else says. No matter who you’re trying to make happy, even if it’s your own family, in the end you’re the only person that you really need in life, and if you can get your ducks in a row and be organized, I really think that you can accomplish what you set your mind to.”
        </p>
        <hr className="my-12 border-t border-slate-300" />

        <section className="text-sm italic text-slate-700 space-y-2">
            <h2 className="font-semibold not-italic text-slate-800 pl-6 -indent-6">Works Cited</h2>
            <p className="pl-6 -indent-6">Trutescu, Christina. Personal interview. Jan. 2022.</p>
            <p className="pl-6 -indent-6">
                Saluan, Paul, and Joseph Styron. <em>“Injury Types and Incidence Rates in Precollegiate Female Gymnasts.”</em> Orthopedic Journal 
            </p>
            <p className="pl-6 -indent-6">
                of Sports Medicine, Apr. 2015.
            </p>
        </section>
      </article>
    </Layout>
  );
}