import Layout from '../Layout';

export default function Vertigo() {
  return (
    <Layout>
      <article className="prose prose-lg lg:prose-xl leading-relaxed indent-8 mx-auto px-4 py-12">
        <h1 className="text-5xl font-extrabold text-center text-slate-900 mb-10 leading-tight">
            Screen Memory and Obsession in Achieving Absolution
        </h1>
        <p>
            Alfred Hitchcock’s Vertigo follows an ex-cop–John “Scottie” Ferguson (James Stewart)–who suffers from severe acrophobia and vertigo due to psychological trauma. The film opens with Scottie and a fellow cop engaged in a rooftop chase after a criminal, where Scottie falls and ends up hanging off the side of a rooftop. When the cop attempts to help Scottie up from the ledge, the cop falls to his death. After the fact, Scottie develops his acrophobia and retires from the force, though soon after is approached by an old colleague, Gavin Elster (Tom Helmore), who tasks Scottie with following Gavin’s wife, Madeleine (Kim Novak). Scottie and Madeleine go on to fall in love, yet Madeleine ends up committing suicide, sending Scottie into a deep depression. He is only pulled out of it after meeting Judy Barton (Kim Novak)–a woman who looks startlingly similar to Madeleine–and forcing her to change until she is a perfect recreation of Scottie’s lost love. Throughout the film, Hitchcock utilizes his famous technique of a dolly zoom, in which the camera is pulled backwards on a dolly while zooming in, to evoke the feeling of Scottie’s vertigo. Besides its literal use, the dolly zoom represents Scottie’s attempt to move forward with Judy, while he’s actually recreating his past with Madeleine. Both women, however, are distractions from the underlying issue in Scottie’s mentality: his vertigo, caused by his guilt over his colleague’s death.
        </p>
        <p>
            Vertigo is defined as a sensation where the world around you is spinning, encapsulating Scottie’s fear of heights as well as his romantic desires, both of which Hitchcock represents through the use of the color green. Scottie first sees Madeleine in Ernie’s restaurant, swathed in green, a color that lies stark against the red-walled background and accordingly, draws the eyes of the audience to her. Madeleine’s jaguar, too, is a green that allows Scottie to tail her through the streets of San Francisco which are filled with monotone colored cars. Resultantly, Scottie begins to associate her with the color, going as far as to wear a green sweater when taking Madeleine back to his house, uncoincidentally the moment in which the audience realizes Scottie has feelings for her. This is no surprise, as from her first appearance, Madeleine is framed as an object of desire. She is so perfect in the eyes of both Scottie and the camera, that she takes on a dreamlike quality. Everything about her, from her graceful, gliding movements, to the picturesque mis-en-scène around her causes Scottie to romanticize her. During this time, Scottie is still healing from his experience on the rooftop and dealing with guilt over his feeling of responsibility for the death of his fellow cop. As such, the idealism Madeleine represents creates an opportunity for escape from the pain of his real life, and thus, she becomes the target of Scottie’s obsession.
        </p>
        <p>
            When Scottie meets Judy, he sees an opportunity for him to recreate Madeleine, and though Judy protests, he changes her looks entirely to fit the image of his ideal woman. While attempting to convince Judy to change, Scottie says “these past few days have been the most happy I’ve been in a year,” to which Judy responds, “I know, ‘cause I remind you of her,” (1:50). Due to how he used Madeleine to escape from his guilt, Scottie ended up depending on being with her for his mental wellbeing. Furthermore, Sigmund Freud believed that “adult fantasies give retrospective shape to memories we attribute to childhood,” and old memories possess a dreamlike quality as a result, a phenomenon Freud called “screen memory” (222-223). In the case of Scottie, by the time he meets Judy, he has built the memory of Madeleine up in his head so much that she is more an idealistic fantasy than a person. Instead of simply remembering Madeleine, he focuses on recreating his screen memory of her with Judy.
        </p>
        <p>
            While Scottie associates Madeleine with the color green, it is also a color commonly linked to illness, and so I believe the color represents both Scottie’s vertigo–his illness–as well as his obsession, both of which can induce a dizzying feeling. The scene in which Madeleine and Scottie share their first kiss has a dreamlike quality, something too perfect to be real. The waves crash in a crescendo that matches the rising, non-diegetic music, and the moment is marked by their unrealistic desires to stay with each other “all the time” (1:05). As such, I believe what we see is not the real moment of the kiss, but rather, Scottie’s screen memory of the moment from later in the film. Once Scottie has changed enough about Judy to turn her into Madeleine’s recreation, they share their first kiss in an almost parallel scene. Judy’s clothes and makeup have been altered to be like that of Madeleine, her hair dyed, and all Scottie requires is to tie her hair up in the swirled bun of her doppelganger. When Judy comes through the bathroom door from fixing her hair, she is almost obscured by the intense green light coming from a sign outside, somehow amplified to make her look more ghost than human. It is as if Madeleine has returned from beyond the grave, wreathed in the color Scottie identifies her with, and so he kisses her. At this moment, the camera spins around them in a movement reminiscent of the feeling of vertigo, and the non-diegetic music is almost the exact same as it was during Scottie’s first kiss with Madeleine.
        </p>
        <p>
            Vertigo displays the entrancing effect of screen memory, and how its hold on Scottie makes him capable of moving past his guilt through obsessing over a woman he builds up to be a fantasy. In a similar fashion, Christopher Nolan’s Memento covers Leonard Shelby’s (Guy Pearce) attempts to avenge his wife’s murder and assault while he deals with complete short-term memory loss every ten minutes. While Memento was released in 2001, 43 years after Vertigo, and the two storylines differ greatly, they both utilize a prominent plot device of the male obsession with an idealized woman, and how she can be used as an escape from guilt. Leonard constantly tells anyone who will listen about how perfect his wife was. He fails to remember the fact that it was he who caused her death. Alternatively, Scottie seeks out a recreation of his “flawless” past lover, who he used as a tool of forgetting his guilt. Both men force their fantasies of an ideal situation onto women, dead and alive, to retrospectively rid them of their subconscious guilt that manifests in separate ways: for Scottie, his guilt lies in his vertigo, while Leonard’s is his obsession with avenging his wife. In the end, the screen memory and resultant obsession displayed by the protagonists of Vertigo and Memento make for a temporary absolution, rooted in viewing women solely as objects of desire.
        </p>
        <hr className="my-12 border-t border-slate-300" />

        <section className="text-sm italic text-slate-700 space-y-2">
            <h2 className="font-semibold not-italic text-slate-800 pl-6 -indent-6">Works Cited</h2>
            <p className="pl-6 -indent-6">Nolan, Christopher. <em>"Memento"</em></p>
            <p className="pl-6 -indent-6">Hitchcock, Alfred. <em>"Vertigo"</em></p>
            <p className="pl-6 -indent-6">
                Sprengnether, Madelon. <em>“Freud as a Memoirist: A Reading of ‘Screen Memories.’”</em> American Imago, Vol. 69, No. 2 
            </p>
        </section>
        </article>
    </Layout>
  );
}