import Layout from '../Layout';

export default function Whipping() {
  return (
    <Layout>
      <article className="prose prose-lg lg:prose-xl leading-relaxed indent-8 mx-auto px-4 py-12">
        <h1 className="text-5xl font-extrabold text-center text-slate-900 mb-10 leading-tight">
          Memory, Time, and the Psychology of Abuse
        </h1>
        <p>
            “The Whipping” by Robert Hayden follows the frenzied flight of a boy before his inevitable capture and beating by a loved one. Within the second line of the poem, it becomes clear that he endures this whipping often, where Hayden writes, “The old woman across the way / is whipping the boy again,” (Hayden, 1, 2). From that moment on the reader is made aware of the ritualism of this beating, which is then enforced by the line “His tears are rainy weather / to woundlike memories:” (11-12). Hayden’s metaphorical explanation of the boy’s tears implies that they represent his reaction to the beating. Furthermore, rainy weather has the ability to cause floods, and so in this line Hayden explains how each beating causes old memories to flood the boy’s brain. Essentially, the boy’s tears are salting and aggravating the mental injuries that exist from previous iterations of the beating. As such, each time that the boy has this experience, all of his traumatic memories from past experiences emerge, adding a mental component to the physical damage and exacerbating the effect of the abuse he undergoes. A defense mechanism of the brain is to hide and repress negative memories from the conscious part of the brain, as they might otherwise overwhelm the person. Each repetition of the trauma–in the boy’s case, a whipping–triggers all the old memories and causes them to resurface from the place that the brain believed safe to store and hide them. Accordingly, through his word choice, Hayden demonstrates the idea of repression, and the effect of repeated trauma on the mental state of victims of abuse.
        </p>
        <p>
            Punctuation is scarce throughout the poem, which aligns with the fast-paced narrative Hayden presents with his imagery of the chase and the beating. In certain lines, Hayden neglects the use of punctuation where in prose, the use of commas would be grammatically correct. For instance, when he writes, “while she in spite of crippling fat pursues and corners him,” (7, 8) the use of punctuation after the words “she,” and, “fat,” would be apt. However, the lack of their presence emphasizes the rushed feeling of the moment. During such a chase, the old woman and the boys’ heartbeats would be accelerated, and adrenaline would be pumping through their systems. Increased adrenaline is taken as a sign of danger by the brain, causing time to seemingly pass faster as a form of escape from a potentially harrowing moment. For the boy, the anxiety associated with the knowledge of the abuse to follow his pursuit would enhance that adrenaline and create a heightened rush of the moment. Through Hayden’s purposeful lack of punctuation– which would otherwise establish breaks within his narration–he conveys the experience of the boy in the moment more effectively by utilizing punctuation as a tool to enforce the rush and speed with which the abuse is delivered. Hayden then places an ellipsis once the beating is over, and then writes, “Well, it is over now, it is over,” (19). This line contains three commas–more punctuation than any previous line in the poem–emphasizing the break as the adrenaline fades. In a fashion similar to a sugar rush, after a large boost in adrenaline, the body is then weakened and the mind slows, producing a contrasting experience to that of during the amplification. The ellipsis demonstrates this feeling and generates the sensation of hearing one’s heartbeat fading and slowing in one’s ears for the reader. The three periods resemble three heartbeats, and I read it as both a slowing in the pace of the poem, as well as a physical sensation for the boy. As such, Hayden uses the ellipsis in two manners, enhancing the reader’s ability to be present in the moment with the boy.
        </p>
        <p>
            The most impactful statement in the poem is one where Hayden encapsulates the entirety of emotions which victims of abuse experience during and after a beating. Between the fourth and fifth stanzas, he writes, “the fear / worse than blows that hateful // Words could bring, the face I / no longer knew or loved…” (15-18). After enduring repeated verbal abuse, ‘hateful words’ begin to lose meaning, in the same manner with which repeating any word out loud causes it to no longer sound real. Additionally, the adrenaline rush and resultant heightened passage of time and heartbeat would prompt a blurring effect on the boy’s auditory senses. As such, those ‘hateful words’ would have less effect than the physical reaction to the raw fear from the combination of resurfacing memories and the ongoing physical abuse. Such intense fear as what the boy experiences would tighten and stiffen his muscles, straining his body during an already harrowing time. That sensation is also tied together with acute anxiety, and both would cause a pit in both his throat and stomach, potentially cutting off his verbal ability. In the second part of the quote, Hayden’s mention of the face the boy no longer loved implies the close relationship with the old woman, and the loss of familiarity with such a visceral betrayal as a whipping. A common trope in the lives of victims is going back to their abusers with the belief that their relationship will change after their brain has suppressed the original trauma of the moment. It is clear that the boy has experienced abuse from the woman before and has loved her at some point. Knowing the typical relationship between abusers and their victims, the boy most likely still loves her, especially when considering the language choice on Hayden’s part. He writes that the old woman’s face is what the boy no longer recognizes but does not state or suggest that the boy no longer loves the woman herself. Hayden’s careful diction, punctuation, and implications throughout “The Whipping” allow for an immersive read through his narration of abuse and lends insight into the experience of victims.
        </p>
        <hr className="my-12 border-t border-slate-300" />

        <section className="text-sm italic text-slate-700 space-y-2">
            <h2 className="font-semibold not-italic text-slate-800 pl-6 -indent-6">Works Cited</h2>
            <p className="pl-6 -indent-6">Hayden, Robert. <em>"The Whipping"</em></p>
        </section>
        </article>
    </Layout>
  );
}